---
- name: Setup InfluxData Repo
  yum_repository:
    name: InfluxDB Repository - RHEL {{ ansible_distribution_major_version }}
    description: InfluxData yum repository
    baseurl: "https://repos.influxdata.com/rhel/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/stable"
    state: present
    enabled: yes
    gpgcheck: yes
    gpgkey: https://repos.influxdata.com/influxdb.key

- name: update yum
  yum:
    name: "*"
    state: latest
    update_only: yes
    update_cache: yes